@startuml CpMl6352
skinparam responseMessageBelowArrow true

title
MediatorManager /v1/provide-mediator-instance
end title

participant "MountingOrchestrator" as MO
participant "MediatorManager://v1/provide-mediator-instance" as MM
database "MediatorManager:ConfigFile" as Config
database "MediatorManager:APPDataFile" as AppData
participant "EricssonMediatorInstanceManagerA://v1/provide-mediator-instance" as MIMListA
participant "EricssonMediatorInstanceManagerA://v1/provide-mediator-instance" as MIMProvideA
participant "EricssonMediatorInstanceManagerB://v1/provide-mediator-instance" as MIMListB
participant "EricssonMediatorInstanceManagerB://v1/provide-mediator-instance" as MIMProvideB


MO -> MM : 
note right MO #PaleGreen
    <b>RequestBody : 
    <b>{
    <b>    device-ip : x.x.x.x,
    <b>    vendor-name : Ericsson,
    <b>    device-model : ML6352
    <b>}
  end note
activate MM

Config --\\o MM : <b>Read attributes from the configuration file
note right MM #LightSteelBlue
<b>allocationMethodType from profile Instance
<b>List of Mediator VM Instances from the LogicalTerminationPoint
end note

AppData --\\o MM : <b>Read attributes from the AppData file
note right MM #LightSteelBlue
<b>mediator-vm-name
<b>vendor-name
<b>supported-device-kind
<b>engineering-limits
end note

 
note over MM 
<b>Filter Mediator VMs that supports the vendor + device-model
end note
note over MM #orange
<b>If allocationMethodType == NONE ?
end note

MM -> MIMListA : get the list of mediator Instances from EricssonMediatorInstanceManagerA
MIMListA -> MM: 200 OK
  note right MM
    [
    {
        "device-name": "MountName",
        "device-kind-name": "ML_6352",
        "mediator-instance-ip-address": "1.1.1.1",
        "mediator-instance-netconf-port": 1,
        "device-ip-address": "1.2.3.4"
    }
    ]
  end note
  note over MM #orange
    <b>If MediatorInstanceCount >= engineering-limits ?
  end note
  note over MM #orange
    YES
  end note
  note over MM
    Checks the next eligible mediator
  end note

MM -> MIMListB : get the list of mediator Instances from EricssonMediatorInstanceManagerB
MIMListB -> MM : 200 OK
  note right MM
    [
    {
        "device-name": "MountName",
        "device-kind-name": "ML_6352",
        "mediator-instance-ip-address": "1.1.1.1",
        "mediator-instance-netconf-port": 1,
        "device-ip-address": "1.2.3.4"
    }
    ]
  end note
  note over MM #orange
    If MediatorInstanceCount >= engineering-limits ?
  end note
  note over MM #orange
    YES
  end note

MM -> MO : 507 Insufficient Storage
 
note over MM #orange
Else
end note

MM -> MIMProvideB : creates new mediator instance
  note left MIMProvideB
    {
  "device-name": "305251234",
  "device-ip-address": "10.118.133.1",
  "device-kind-name": "AGS_20"
    }
  end note

MIMProvideB ->  MM : 200 OK
    note right MM
    {
    "mediator-instance-ip-address": "10.118.132.1",
    "mediator-instance-netconf-port": 1
    }
    end note

MM -> MO : 200 OK
    note left MM
    {
    "mediator-instance-ip-address": "10.118.132.1",
    "mediator-instance-netconf-port": 1
    }
    end note

@enduml